export const tableHeadersApplicantOverview = [
  {
    keyName: '#',
    keyValue: 'index',
    className: 'fw-normal',
    showColumn: true,
    key: 0,
  },
  {
    keyName: '#',
    keyValue: 'id',
    className: 'fw-normal',
    showColumn: false,
    key: 1,
  },
  {
    keyName: 'Name',
    keyValue: 'fullName',
    className: '',
    showColumn: true,
    key: 2,
  },
  {
    keyName: 'Age',
    keyValue: 'age',
    className: 'fw-medium',
    showColumn: true,
    key: 3,
  },
  {
    keyName: 'Gender',
    keyValue: 'gender',
    className: 'fw-medium',
    showColumn: true,
    key: 4,
  },
  {
    keyName: 'Registration Status',
    keyValue: 'status',
    className: 'w-25',
    showColumn: true,
    key: 5,
  },
  {
    keyName: 'Document Status',
    keyValue: 'documentStatus',
    className: '',
    showColumn: true,
    key: 6,
  },
];
