export const tableHeadersApplicant = [
  {
    keyName: 'Name',
    keyValue: 'fullName',
    className: 's',
    showColumn: true,
    key: 0,
  },
  {
    keyName: 'Age',
    keyValue: 'age',
    className: '',
    showColumn: true,
    key: 1,
  },
  {
    keyName: 'Gender',
    keyValue: 'gender',
    className: '',
    showColumn: true,
    key: 3,
  },
  {
    keyName: 'Relationship',
    keyValue: 'relationToPatient',
    className: '',
    showColumn: true,
    key: 4,
  },
  {
    keyName: 'Mobile',
    keyValue: 'mobile',
    className: '',
    showColumn: true,
    key: 5,
  },
  {
    keyName: 'Email',
    keyValue: 'email',
    className: '',
    showColumn: true,
    key: 6,
  },
  {
    keyName: '',
    keyValue: 'button',
    className: '',
    showColumn: true,
    key: 7,
  },
];
export const tableHeadersReview = [
  {
    keyName: 'Name',
    keyValue: 'fullName',
    className: 's',
    showColumn: true,
    key: 0,
  },
  {
    keyName: 'Age',
    keyValue: 'age',
    className: '',
    showColumn: true,
    key: 1,
  },
  {
    keyName: 'Gender',
    keyValue: 'gender',
    className: '',
    showColumn: true,
    key: 3,
  },
  {
    keyName: 'Relationship',
    keyValue: 'relationToPatient',
    className: '',
    showColumn: true,
    key: 4,
  },
  {
    keyName: 'Mobile',
    keyValue: 'mobile',
    className: '',
    showColumn: true,
    key: 5,
  },
  {
    keyName: 'Email',
    keyValue: 'email',
    className: '',
    showColumn: true,
    key: 6,
  },
];
export const tableHeadersVbcApplicant = [
  {
    keyName: 'Name',
    keyValue: 'fullName',
    className: '',
    showColumn: true,
    key: 0,
  },
  {
    keyName: 'Relationship',
    keyValue: 'relationToPatient',
    className: '',
    showColumn: true,
    key: 1,
  },
  {
    keyName: 'Mobile',
    keyValue: 'mobile',
    className: '',
    showColumn: true,
    key: 2,
  },
  {
    keyName: 'Email',
    keyValue: 'email',
    className: '',
    showColumn: true,
    key: 3,
  },
  {
    keyName: 'Registration Status',
    keyValue: 'status',
    className: '',
    showColumn: true,
    key: 4,
  },
  {
    keyName: 'Document Status',
    keyValue: 'documentStatus',
    className: '',
    showColumn: true,
    key: 5,
  },
  {
    keyName: '',
    keyValue: 'button',
    className: '',
    showColumn: true,
    key: 6,
  },
];
export const tableHeadersVbcCaregiver = [
  {
    keyName: 'Name',
    keyValue: 'fullName',
    className: '',
    showColumn: true,
    key: 0,
  },
  {
    keyName: 'Relationship',
    keyValue: 'relationToPatient',
    className: '',
    showColumn: true,
    key: 1,
  },
  {
    keyName: 'Mobile',
    keyValue: 'mobile',
    className: '',
    showColumn: true,
    key: 2,
  },
  {
    keyName: 'Email',
    keyValue: 'email',
    className: '',
    showColumn: true,
    key: 3,
  },
  {
    keyName: 'Registration Status',
    keyValue: 'status',
    className: '',
    showColumn: true,
    key: 4,
  },
  {
    keyName: 'Document Status',
    keyValue: 'documentStatus',
    className: '',
    showColumn: false,
    key: 5,
  },
  {
    keyName: '',
    keyValue: 'button',
    className: '',
    showColumn: true,
    key: 6,
  },
];
