export const tableHeadersMangoPatient = [
  {
    keyName: 'Patient Id',
    keyValue: 'uniqueId',
    label: 'Patient Id',
    value: 'uniqueId',
    className: '',
    showColumn: true,
    key: 0,
  },
  {
    keyName: 'Name',
    keyValue: 'fullName',
    label: 'Name',
    value: 'fullName',
    className: '',
    showColumn: true,
    key: 1,
  },
  {
    keyName: 'MRN',
    keyValue: 'mrn',
    label: 'MRN',
    value: 'mrn',
    className: '',
    showColumn: true,
    key: 2,
  },
  {
    keyName: 'Mobile',
    keyValue: 'mobileNumber',
    label: 'Mobile',
    value: 'mobileNumber',
    className: '',
    showColumn: true,
    key: 3,
  },
  {
    keyName: 'Email',
    keyValue: 'email',
    label: 'Email',
    value: 'email',
    className: '',
    showColumn: true,
    key: 4,
  },
  {
    keyName: 'Hospital Group',
    keyValue: 'hospitalGroupName',
    label: 'Hospital Group',
    value: 'hospitalGroupName',
    className: 'name',
    showColumn: true,
    key: 5,
  },
  {
    keyName: 'Hospital Unit',
    keyValue: 'hospitalUnitName',
    label: 'Hospital Unit',
    value: 'hospitalUnitName',
    className: 'name',
    showColumn: true,
    key: 6,
  },
  {
    keyName: 'Doctor',
    keyValue: 'doctorName',
    label: 'Doctor',
    value: 'doctorName',
    className: 'name',
    showColumn: true,
    key: 7,
  },
  {
    keyName: 'Drug',
    keyValue: 'drugName',
    label: 'Drug',
    value: 'drugName',
    className: 'name',
    showColumn: true,
    key: 8,
  },
  {
    keyName: 'Status',
    keyValue: 'patientStatus',
    label: 'Status',
    value: 'patientStatus',
    className: '',
    showColumn: true,
    key: 9,
  },
  {
    keyName: 'Actions',
    keyValue: 'edit',
    label: 'Actions',
    value: 'edit',
    className: '',
    showColumn: true,
    key: 10,
  },
];
export const tableHeadersMangoIncompletePatients = [
  {
    keyName: 'S/N',
    keyValue: 'sn',
    className: 'name',
    showColumn: true,
    key: 0,
  },
  {
    keyName: 'Name',
    keyValue: 'fullName',
    className: '',
    showColumn: true,
    key: 1,
  },

  {
    keyName: 'Mobile',
    keyValue: 'mobile',
    className: '',
    showColumn: true,
    key: 3,
  },
  {
    keyName: 'Email',
    keyValue: 'email',
    className: '',
    showColumn: true,
    key: 4,
  },
  {
    keyName: 'Date',
    keyValue: 'date',
    className: '',
    showColumn: true,
    key: 5,
  },
];
export const tableHeadersMangoPendingApprovalPatients = [
  {
    keyName: 'Name',
    keyValue: 'name',
    className: 'p-2',
    showColumn: true,
    key: 1,
  },

  {
    keyName: 'Mobile',
    keyValue: 'mobile',
    className: '',
    showColumn: true,
    key: 3,
  },
  {
    keyName: 'Email',
    keyValue: 'email',
    className: '',
    showColumn: true,
    key: 4,
  },
  {
    keyName: 'Date',
    keyValue: 'date',
    className: '',
    showColumn: true,
    key: 5,
  },
  {
    keyName: 'Action',
    keyValue: 'act',
    className: '',
    showColumn: true,
    key: 6,
  },
];
export const tableHeadersDoctorPatients = [
  {
    keyName: 'Name',
    keyValue: 'fullName',
    label: 'Name',
    value: 'fullName',
    className: '',
    showColumn: true,
    key: 1,
  },
  {
    keyName: 'MRN',
    keyValue: 'mrn',
    label: 'MRN',
    value: 'mrn',
    className: '',
    showColumn: true,
    key: 2,
  },

  {
    keyName: 'Hospital Group',
    keyValue: 'hospitalGroupName',
    label: 'Hospital Group',
    value: 'hospitalGroupName',
    className: 'name',
    showColumn: true,
    key: 4,
  },
  {
    keyName: 'Hospital Unit',
    keyValue: 'hospitalUnitName',
    label: 'Hospital Unit',
    value: 'hospitalUnitName',
    className: 'name',
    showColumn: true,
    key: 5,
  },
  {
    keyName: 'Doctor',
    keyValue: 'doctorName',
    label: 'Doctor',
    value: 'doctorName',
    className: 'name',
    showColumn: true,
    key: 6,
  },
  {
    keyName: 'Drug',
    keyValue: 'drugName',
    label: 'Drug',
    value: 'drugName',
    className: 'name',
    showColumn: true,
    key: 7,
  },
  {
    keyName: 'Status',
    keyValue: 'patientStatus',
    label: 'Status',
    value: 'patientStatus',
    className: '',
    showColumn: true,
    key: 8,
  },
  {
    keyName: 'Actions',
    keyValue: 'edit',
    label: 'Actions',
    value: 'edit',
    className: '',
    showColumn: true,
    key: 9,
  },
];
export const tableHeadersPastGrantAmountAndDate = [
  {
    keyName: 'Cycle #',
    keyValue: 'cycleNo',
    label: 'Cycle #',
    value: 'cycleNo',
    className: '',
    showColumn: true,
    key: 1,
  },
  {
    keyName: 'Grant Amount',
    keyValue: 'grantAmountDisplay',
    label: 'Grant Amount',
    value: 'grantAmountDisplay',
    className: '',
    showColumn: true,
    key: 2,
  },

  {
    keyName: 'Grant Sent Date',
    keyValue: 'grantSentDateDisplay',
    label: 'Grant Sent Date',
    value: 'grantSentDateDisplay',
    className: 'name',
    showColumn: true,
    key: 3,
  },
  {
    keyName: 'Upload Receipt',
    keyValue: 'uploadReceipt',
    label: 'Upload Receipt',
    value: 'uploadReceipt',
    className: 'name',
    showColumn: true,
    key: 4,
  },
];
