export const DATA_TYPE = {
  NUMBER: 'NUMBER',
  STRING: 'STRING',
  ARRAY: 'ARRAY',
  OBJECT: 'OBJECT',
  BOOLEAN: 'BOOLEAN',
};

export const searchOperation = {
  EQUAL_TO: 'EQUAL_TO',
  GREATER_THAN: 'GREATER_THAN',
  LESS_THAN: 'LESS_THAN',
  LIKE: 'LIKE',
  STARTS_WITH: 'STARTS_WITH',
  IN: 'IN',
  GREATER_THAN_EQUAL_TO: 'GREATER_THAN_EQUAL_TO',
  LESS_THAN_EQUAL_TO: 'LESS_THAN_EQUAL_TO',
  ENDS_WITH: 'ENDS_WITH',
  ILIKE: 'ILIKE',
  IS_NULL: 'IS_NULL',
};

export const VALIDATE_DATE_TYPE = {
  RESTRICT_PAST_DATE: 'RESTRICT_PAST_DATE',
  RESTRICT_PAST_DATE_EXCLUDING_CURRENT: 'RESTRICT_PAST_DATE_EXCLUDING_CURRENT',
  RESTRICT_FUTURE_DATE: 'RESTRICT_FUTURE_DATE',
  RESTRICT_FUTURE_DATE_EXCLUDING_CURRENT:
    'RESTRICT_FUTURE_DATE_EXCLUDING_CURRENT',
  ONLY_CURRENT_DATE: 'ONLY_CURRENT_DATE',
};

export const MASTER_DATA_FIELDS = {
  BANKS: 'banks',
  CANCER_TYPES: 'cancerTypes',
  COMPANY_TYPES: 'companyTypes',
  COUNTRIES: 'countries',
  EMPLOYERS: 'employers',
  EXPERIENCES: 'experiences',
  GROSS_ANNUAL_INCOME: 'grossAnnualIncomes',
  INDUSTRY_TYPES: 'industryTypes',
  INSURANCE_COMPANIES: 'insuranceCompanies',
  LANGUAGES: 'languages',
  NATURE_OF_BUSINESS: 'natureOfBusinesses',
  OCCUPATIONS: 'occupations',
  PROFESSIONS: 'professions',
  RESIDENCE_TYPES: 'residenceTypes',
  STATES: 'states',
  YEARS_IN_BUSINESS: 'yearsInBusinesses',
  INCOME_RANGE_LIST: 'incomeRangeList',
  EDUCATION_LEVEL_LIST: 'educationLevelList',
  RELATIONSHIPS: 'relationships',
  DOCTOR_CHANGE_REASONS: 'doctorChangeReasons',
  CLINICAL_DROP_OUT: 'clinicalDropReasons',
  NON_CLINICAL_DROP_OUT: 'nonClinicalDropReasons',
  PATIENT_STATUSES: 'patientStatuses',
};

export const MASTER_DATA_STATE_COUNTRY = [
  MASTER_DATA_FIELDS.STATES,
  MASTER_DATA_FIELDS.COUNTRIES,
];
export const MASTER_DATA_COMPLETE_PROFILE = [
  MASTER_DATA_FIELDS.STATES,
  MASTER_DATA_FIELDS.COUNTRIES,
  MASTER_DATA_FIELDS.CANCER_TYPES,
  MASTER_DATA_FIELDS.RELATIONSHIPS,
];
export const MASTER_DATA_ME = [
  MASTER_DATA_FIELDS.PATIENT_STATUSES,
  MASTER_DATA_FIELDS.CLINICAL_DROP_OUT,
  MASTER_DATA_FIELDS.NON_CLINICAL_DROP_OUT,
  MASTER_DATA_FIELDS.DOCTOR_CHANGE_REASONS,
  MASTER_DATA_FIELDS.RELATIONSHIPS,
];

export const MASTER_DATA_FINANCE_PATIENT = [
  MASTER_DATA_FIELDS.EDUCATION_LEVEL_LIST,
  MASTER_DATA_FIELDS.PROFESSIONS,
  MASTER_DATA_FIELDS.EMPLOYERS,
  MASTER_DATA_FIELDS.INDUSTRY_TYPES,
  MASTER_DATA_FIELDS.INSURANCE_COMPANIES,
  MASTER_DATA_FIELDS.RELATIONSHIPS,
];

export const MASTER_DATA_FINANCE_APPLICANT = [
  MASTER_DATA_FIELDS.EMPLOYERS,
  MASTER_DATA_FIELDS.PROFESSIONS,
  MASTER_DATA_FIELDS.INDUSTRY_TYPES,
  MASTER_DATA_FIELDS.BANKS,
  MASTER_DATA_FIELDS.EMPLOYERS,
  MASTER_DATA_FIELDS.COMPANY_TYPES,
  MASTER_DATA_FIELDS.NATURE_OF_BUSINESS,
  MASTER_DATA_FIELDS.INDUSTRY_TYPES,
  MASTER_DATA_FIELDS.OCCUPATIONS,
  MASTER_DATA_FIELDS.RESIDENCE_TYPES,
];

export const DOCUMENT_TYPE = {
  CANCELLED_CHEQUE: 'Cancelled Cheque',
};
export const DOCUMENT = {
  FINANCIAL: 'FINANCIAL',
  MEDICAL: 'MEDICAL',
};

export const VERSION_TYPE = {
  ANDROID: 'ANDROID',
  IOS: 'IOS',
  BACKEND: 'BACKEND',
};

export const GRANT_AMOUNT_TYPE = {
  PERCENT: 'PERCENT',
  FIXED: 'FIXED',
};
export const selectGrantAmountTypeOptions = [
  {
    id: 'percentage',
    label: 'Percentage(%)',
    value: GRANT_AMOUNT_TYPE.PERCENT,
  },
  {
    id: 'fixed',
    label: 'Fixed',
    value: GRANT_AMOUNT_TYPE.FIXED,
  },
];
export const CANCER_TYPES = [MASTER_DATA_FIELDS.CANCER_TYPES];
