import {DATA_TYPE, searchOperation} from '../constants';

export const filters = [
  {id: 1, name: 'User Id', value: 'id', fieldType: 'number'},
  {
    id: 2,
    name: 'User role',
    value: 'role',
    fieldType: 'select',
    options: [
      {id: 1, label: 'Admin', value: 'admin'},
      {id: 2, label: 'Doctor', value: 'doctor'},
      {id: 3, label: 'Patient', value: 'patient'},
    ],
  },
];
export const mangoExecutivefilters = [
  {
    id: 1,
    name: 'Name',
    value: 'fullName',
    fieldType: 'text',
    dataType: DATA_TYPE.STRING,
    searchKey: 'fullName',
    displayValue: 'Name',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 1.2,
    name: 'Patient Id',
    value: 'uniqueId',
    fieldType: 'text',
    displayValue: 'PatientId',
    dataType: DATA_TYPE.STRING,
    searchKey: 'uniqueId',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 2,
    name: 'MRN',
    value: 'mrn',
    fieldType: 'text',
    dataType: DATA_TYPE.STRING,
    searchKey: 'mrn',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 3,
    name: 'Hospital Group',
    value: 'hospitalGroup',
    fieldType: 'select',
    options: [],
    dataType: DATA_TYPE.STRING,
    searchKey: 'hospitalGroup',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
  },
  {
    id: 4,
    name: 'Hospital Unit',
    value: 'hospitalId',
    fieldType: 'select',
    options: [],
    dataType: DATA_TYPE.NUMBER,
    searchKey: 'hospitalId',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
  },
  {
    id: 5,
    name: 'Doctor',
    value: 'doctorId',
    fieldType: 'select',
    options: [],
    dataType: DATA_TYPE.NUMBER,
    searchKey: 'doctorId',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
  },
  {
    id: 6,
    name: 'Drug',
    value: 'drugId',
    fieldType: 'select',
    options: [],
    dataType: DATA_TYPE.NUMBER,
    searchKey: 'drugId',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
  },
  {
    id: 7,
    name: 'Status',
    value: 'status',
    fieldType: 'select',
    options: [],
    dataType: DATA_TYPE.STRING,
    searchKey: 'status',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 8,
    name: 'Mobile',
    value: 'mobile',
    maxLength: 10,
    fieldType: 'number',
    options: [],
    dataType: DATA_TYPE.STRING,
    searchKey: 'mobile',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 9,
    name: 'Email',
    value: 'email',
    maxLength: 10,
    fieldType: 'text',
    options: [],
    dataType: DATA_TYPE.STRING,
    searchKey: 'email',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
];
export const mangoExecutiveInCompletefilters = [
  {
    id: 1,
    name: 'Name',
    value: 'firstName',
    fieldType: 'text',
    dataType: DATA_TYPE.STRING,
    displayValue: 'Name',
    searchKey: 'firstName',
    searchOperation: searchOperation.ILIKE,
    orOperation: true,
  },
  {
    id: 2,
    name: 'Email Id',
    value: 'email',
    fieldType: 'text',
    dataType: DATA_TYPE.STRING,
    searchKey: 'email',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 3,
    name: 'Mobile',
    value: 'mobile',
    maxLength: 10,
    fieldType: 'number',
    options: [],
    dataType: DATA_TYPE.STRING,
    searchKey: 'mobile',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
];
export const mangoExecutiveRegistrationRequiredfilters = [
  {
    id: 1,
    name: 'Name',
    value: 'fullname',
    fieldType: 'text',
    dataType: DATA_TYPE.STRING,
    displayValue: 'Name',
    searchKey: 'name',
    useValueToRemove: true,
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 2,
    name: 'Email Id',
    value: 'email',
    fieldType: 'text',
    dataType: DATA_TYPE.STRING,
    searchKey: 'email',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 3,
    name: 'Mobile',
    value: 'mobile',
    maxLength: 10,
    fieldType: 'number',
    options: [],
    dataType: DATA_TYPE.STRING,
    searchKey: 'mobile',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  // {
  //   id: 4,
  //   name: 'Accepted',
  //   value: 'accepted',
  //   maxLength: 10,
  //   fieldType: 'select',
  //   options: [],
  //   dataType: DATA_TYPE.BOOLEAN,
  //   searchKey: 'accepted',
  //   searchOperation: searchOperation.IS_NULL,
  //   orOperation: false,
  // },
];
export const doctorFilters = [
  {
    id: 1,
    name: 'Name',
    value: 'fullName',
    fieldType: 'text',
    dataType: DATA_TYPE.STRING,
    searchKey: 'fullName',
    displayValue: 'Name',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 2,
    name: 'MRN',
    value: 'mrn',
    fieldType: 'text',
    dataType: DATA_TYPE.STRING,
    searchKey: 'mrn',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 3,
    name: 'Drug',
    value: 'drugId',
    fieldType: 'select',
    options: [],
    dataType: DATA_TYPE.NUMBER,
    searchKey: 'drugId',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
  },
  {
    id: 4,
    name: 'Status',
    value: 'status',
    fieldType: 'select',
    options: [],
    dataType: DATA_TYPE.STRING,
    searchKey: 'status',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
];
export const userFilter = [
  {
    id: 1,
    name: 'Name',
    value: 'fullName',
    fieldType: 'text',
    dataType: DATA_TYPE.STRING,
    searchKey: 'fullName',
    displayValue: 'Name',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 2,
    name: 'Mobile Number',
    value: 'mobile',
    fieldType: 'text',
    dataType: DATA_TYPE.STRING,
    searchKey: 'mobile',
    orOperation: false,
    searchOperation: searchOperation.ILIKE,
  },
];
export const hospitalFilter = [
  {
    id: 1,
    name: 'Hospital Name',
    value: 'hospitalName',
    dataType: DATA_TYPE.STRING,
    searchKey: 'hospitalName',
    fieldType: 'text',
    orOperation: false,
    searchOperation: searchOperation.ILIKE,
  },
  {
    id: 2,
    name: 'Hospital Group Name',
    value: 'hospitalGroupName',
    dataType: DATA_TYPE.STRING,
    searchKey: 'hospitalGroupName',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
];
export const userDoctorFilter = [
  {
    id: 1,
    name: 'Name',
    value: 'fullName',
    dataType: DATA_TYPE.STRING,
    searchKey: 'fullName',
    fieldType: 'text',
    displayValue: 'Name',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 2,
    name: 'Mobile',
    value: 'mobile',
    dataType: DATA_TYPE.STRING,
    searchKey: 'mobile',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 3,
    name: 'Hospital Unit',
    value: 'hospitalId',
    dataType: DATA_TYPE.NUMBER,
    searchKey: 'hospitalId',
    fieldType: 'select',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
    options: [],
  },
  {
    id: 4,
    name: 'Hospital Group',
    value: 'hospitalGroup',
    dataType: DATA_TYPE.STRING,
    searchKey: 'hospitalGroup',
    fieldType: 'select',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
    options: [],
  },
];
export const drugsFilter = [
  {
    id: 1,
    name: 'Brand Name',
    value: 'brandName',
    dataType: DATA_TYPE.STRING,
    searchKey: 'brandName',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 2,
    name: 'Generic Name',
    value: 'drugGenericName',
    dataType: DATA_TYPE.STRING,
    searchKey: 'drugGenericName',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 3,
    name: 'Manufacturer',
    value: 'manufacturerId',
    dataType: DATA_TYPE.NUMBER,
    searchKey: 'manufacturer',
    useValueToRemove: true,
    fieldType: 'select',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
    options: [],
  },
  {
    id: 4,
    name: 'Diagnosis',
    value: 'diagnosis',
    dataType: DATA_TYPE.STRING,
    searchKey: 'diagnosis',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
];

export const routesFilter = [
  {
    id: 1,
    name: 'Route Name',
    value: 'routeName',
    dataType: DATA_TYPE.STRING,
    searchKey: 'name',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 2,
    name: 'Component Name',
    value: 'component',
    dataType: DATA_TYPE.STRING,
    searchKey: 'component',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
];
export const resourcesFilter = [
  {
    id: 1,
    name: 'Resources Name',
    value: 'resourceName',
    dataType: DATA_TYPE.STRING,
    searchKey: 'name',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
    useValueToRemove: true,
  },
  {
    id: 2,
    name: 'Resource Description',
    value: 'description',
    dataType: DATA_TYPE.STRING,
    searchKey: 'description',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
];
export const permissionFilter = [
  {
    id: 1,
    name: 'Permission Name',
    value: 'action',
    dataType: DATA_TYPE.STRING,
    searchKey: 'action',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 2,
    name: 'Description',
    value: 'description',
    dataType: DATA_TYPE.STRING,
    searchKey: 'description',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
];
export const pbpProgramFilter = [
  {
    id: 1,
    name: 'Name',
    value: 'programName',
    dataType: DATA_TYPE.STRING,
    searchKey: 'programName',
    fieldType: 'text',
    searchOperation: searchOperation.ILIKE,
    orOperation: false,
  },
  {
    id: 2,
    name: 'Drug',
    value: 'drugId',
    dataType: DATA_TYPE.NUMBER,
    searchKey: 'vbcDrugMaster',
    fieldType: 'select',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
  },
  {
    id: 3,
    name: 'Hospital Unit',
    value: 'hospitalId',
    dataType: DATA_TYPE.NUMBER,
    searchKey: 'hospital',
    fieldType: 'select',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
    useValueToRemove: true,
  },
  {
    id: 4,
    name: 'Manufacturer',
    value: 'manufacturerId',
    dataType: DATA_TYPE.NUMBER,
    searchKey: 'manufacturer',
    fieldType: 'select',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
    useValueToRemove: true,
  },
];
export const iosVersionListFilter = [
  {
    id: 1,
    name: 'IOS Version',
    value: 'iosVersion',
    dataType: DATA_TYPE.STRING,
    searchKey: 'iosVersion',
    fieldType: 'text',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
  },
];
export const androidVersionFilter = [
  {
    id: 1,
    name: 'Android Version',
    value: 'androidVersion',
    dataType: DATA_TYPE.STRING,
    searchKey: 'androidVersion',
    fieldType: 'text',
    searchOperation: searchOperation.EQUAL_TO,
    orOperation: false,
  },
];
