/**
 * This module contains all the endpoints in the application Backend.
 * Always try to add new endpoint in the end.
 */
const adminEndPoint = 'vbc-admin';
const mangoExecutiveEndPoint = 'vbc-admin/mango-executive';
const patientDataEndPoint = 'vbc-patient-data/api';
const patientEndPoint = 'vbc-patient/api';
const applicantEndPoint = 'vbc-patient/applicant';
const pharmaEndPoint = 'vbc-pharma';
const documentEndPoint = 'vbc-document/document';
const doctorEndPoint = 'vbc-doctor/doctor';
const notificationEndPoint = 'vbc-notification/api';

export const endpoints = {
  //PATIENT_DATA_APIS
  PATIENT_TIMELINE_URL: `${patientDataEndPoint}/patienttimeline/url`,
  SURGICAL_DETAILS: `${patientDataEndPoint}/surgery`,
  MEDICATION: `${patientDataEndPoint}/medication`,
  CLINICAL_NOTES: `${patientDataEndPoint}/notes`,
  SUMMARY_NOTES: `${patientDataEndPoint}/summaries`,
  LABS_REPORTS: `${patientDataEndPoint}/lab`,
  RADIOLOGY_REPORTS: `${patientDataEndPoint}/radiologies`,
  OTHER_TESTS: `${patientDataEndPoint}/other-tests`,
  RADIATION_THERAPY: `${patientDataEndPoint}/radiation-therapy`,
  OTHER_TREATMENT: `${patientDataEndPoint}/other-treatment`,
  GET_REPORT_SYNC_FLAG: `${patientDataEndPoint}/check-data-synchronization?userid={0}`,
  //PATIENT API
  PATIENT_REGISTER: `${patientEndPoint}/register`,
  RESEND_OTP: `${patientEndPoint}/resend-otp`,
  VERIFY_PATIENT: `${patientEndPoint}/register/verify`,
  RESET_PASSWORD: `${patientEndPoint}/reset-password`,
  HOSPITAL_LIST: `${patientEndPoint}/hospitals`,
  DRUG_LIST: `${patientEndPoint}/drugs`,
  DOCTOR_LIST: `${patientEndPoint}/doctors/{hospitalId}`,
  COMPLETE_PROFILE: `${patientEndPoint}/complete-your-profile`,
  PATIENT_PROFILE: `${patientEndPoint}/your-details`,
  PATIENT_PROFILE_UPDATE: `${patientEndPoint}/profile/update`,
  GET_AMOUNT: `${patientEndPoint}/get-amount`,
  ENROLL_FOR_VBC: `${patientEndPoint}/enroll-for-vbc`,
  GET_FINANCIAL_INFORMATION: `${patientEndPoint}/get-financial-information`,
  GET_ENROLL_FOR_VBC: `${patientEndPoint}/get-enrollment-data`,
  UPDATE_FINANCIAL_INFORMATION: `${patientEndPoint}/update-financial-information`,
  READ_APPLICANTS_LIST: `${patientEndPoint}/applicants`,
  CREATE_APPLICANT: `${patientEndPoint}/applicant/add`,
  UPDATE_APPLICANT: `${patientEndPoint}/applicant/edit`,
  DELELTE_APPLICANT: `${patientEndPoint}/applicant/remove`,
  MASTER_DATA: `${patientEndPoint}/master-data`,
  GET_CITY_DATA: `${patientEndPoint}/cities/{stateId}`,
  VBC_PROGRAM_STEP_ONE: `${patientEndPoint}/enroll-for-vbc/step-one`,
  VBC_PROGRAM_STEP_TWO: `${patientEndPoint}/enroll-for-vbc/step-two`,
  VBC_PROGRAM_STEP_THREE: `${patientEndPoint}/enroll-for-vbc/step-three`,
  VBC_PROGRAM_STEP_FOUR: `${patientEndPoint}/enroll-for-vbc/step-four`,
  GET_SCHEDULE: `${patientEndPoint}/schedule`,
  GET_VBC_DRUG_SCHEDULE: `${patientEndPoint}/drug-schedule`,
  ACKNOWLEDGE_FIRST_GRANT: `${patientEndPoint}/acknowledge-first-grant`,
  CANCLE_APPLICATION: `${patientEndPoint}/cancel-application`,
  REAPPLY_APPLICATION: `${patientEndPoint}/reapply-application`,
  SUBMIT_TO_MANGO_EXECUTIVE: `${patientEndPoint}/submit-to-mango-executive`,
  VERIFY_PATIENT_OTP: `${patientEndPoint}/verify-contact-details`,
  SEND_PATIENT_OTP: `${patientEndPoint}/send-verification-otp`,
  //APPLICANT
  APPLICANT_COMPLETE_PROFILE: `${applicantEndPoint}/profile/update`,
  APPLICANT_PROFILE: `${applicantEndPoint}/profile/details`,
  APPLICANT_PROFILE_UPDATE: `${applicantEndPoint}/profile/update`,
  GET_APPLICANT_AMOUNT: `${applicantEndPoint}/get-loan-amount`,
  GET_LOAN_DETAIL: `${applicantEndPoint}/loan-application/details`,
  START_LOAN_APPLICATION: `${applicantEndPoint}/loan-application/final-submit`,
  GET_APPLICANT_FINANCIAL_INFORMATION: `${applicantEndPoint}/financial-data/details`,
  UPDATE_APPLICANT_FINANCIAL_INFORMATION: `${applicantEndPoint}/financial-data/update`,
  GET_APPLICANT_OVERVIEW: `${applicantEndPoint}/loan-application/overview`,
  APPLICANT_LOAN_APPLICATION_STEP_ONE: `${applicantEndPoint}/loan-application/step-one`,
  APPLICANT_LOAN_APPLICATION_STEP_TWO: `${applicantEndPoint}/loan-application/step-two`,
  APPLICANT_LOAN_APPLICATION_STEP_THREE: `${applicantEndPoint}/loan-application/step-three`,
  APPLICANT_LOAN_APPLICATION_STEP_FOUR: `${applicantEndPoint}/loan-application/step-four`,
  VERIFY_APPLICANT_OTP: `${applicantEndPoint}/verify-contact-details`,
  SEND_APPLICANT_OTP: `${applicantEndPoint}/send-verification-otp`,
  //NOTIFICATION
  GET_NOTIFICATIONS: `${notificationEndPoint}/notifications`,
  MARK_NOTIFICATION_READ: `${notificationEndPoint}/notifications/mark-read`,
  SEND_PUSH_NOTIFICATION: `${notificationEndPoint}/pushnotification`,
  //MANGO EXECUTIVE
  MANGO_EXECUTIVE_PATIENT_LIST: `${mangoExecutiveEndPoint}/patients`,
  REBATE_PAID: `${mangoExecutiveEndPoint}/mark-rebate-paid?patientId={0}`,
  PENDING_PATIENT_LIST: `${mangoExecutiveEndPoint}/pending-patient-registrations`,
  APPROVAL_REG_REQ_LIST: `${mangoExecutiveEndPoint}/registration-requests`,
  HANDLE_REG_REQUEST: `${mangoExecutiveEndPoint}/handle-registration-request`,
  GET_MANGO_EXECUTIVE_PATIENT_DETAILS: `${mangoExecutiveEndPoint}/patient-detail`,
  UPDATE_PATIENT_STATUS_TO_AWARE: `${mangoExecutiveEndPoint}/update-patient-status-to-aware`,
  ASSIGN_APPOINTMENT_DATE_TO_PATIENT: `${mangoExecutiveEndPoint}/assign-appointment-date-to-patient`,
  ASSIGN_DOCTOR_TO_PATIENT: `${mangoExecutiveEndPoint}/assign-doctor-to-patient`,
  ASSIGN_LENDER_TO_PATIENT: `${mangoExecutiveEndPoint}/assign-lender-to-patient`,
  MANGO_EXECUTIVE_ADD_PATIENT: `${mangoExecutiveEndPoint}/add-patient`,
  ASSIGN_TREATMENT_DATE_TO_PATIENT: `${mangoExecutiveEndPoint}/assign-treatment-start-date-for-patient`,
  PAUSE_TREATMENT_FOR_PATIENT: `${mangoExecutiveEndPoint}/pause-treatment-for-patient`,
  RESTART_TREATMENT_FOR_PATIENT: `${mangoExecutiveEndPoint}/restart-treatment-for-patient`,
  TERMINATE_TREATMENT_FOR_PATIENT: `${mangoExecutiveEndPoint}/terminate-treatment-for-patient`,
  COMPLETE_TREATMENT_FOR_PATIENT: `${mangoExecutiveEndPoint}/complete-patient-treatment`,
  APPROVE_LOAN: `${mangoExecutiveEndPoint}/approve-loan-for-patient`,
  REJECT_LOAN: `${mangoExecutiveEndPoint}/reject-loan-for-patient`,
  UPDATE_PATIENT_INTERACTION: `${mangoExecutiveEndPoint}/update-patient-interaction`,
  ADD_DRUR_RECEIPT_AMOUNT: `${mangoExecutiveEndPoint}/add-drug-receipt-amount`,
  ACKNOWLWDGE_REBATE_PAID: `${mangoExecutiveEndPoint}/acknowledge-rebate-paid/{0}`,
  ACKNOWLWDGE_SUBVENTION_PAID: `${mangoExecutiveEndPoint}/acknowledge-subvention-paid/{0}`,
  MARK_DRUG_SCHEDULE_GRANT: `${mangoExecutiveEndPoint}/mark-drug-schedule-grant-paid`,
  UPDATE_DATA_CONSENT: `${mangoExecutiveEndPoint}/update-patient-data-consent-date/{id}`,
  TRIGGER_GRANT_EMAIL: `${mangoExecutiveEndPoint}/manually-trigger-grant-email`,
  GET_ELIGIBLE_CYCLE_FOR_CONVERSION: `${mangoExecutiveEndPoint}/list-convertible-patient-cycles?patientId={0}`,
  SWITCH_PAYMENT_TYPE: `${mangoExecutiveEndPoint}/switch-payment-type`,
  //ADMIN_APIS
  HOSPITAL_GROUP_LIST: `${adminEndPoint}/hospital/get-groups`,
  UPDATE_RESOURCE_PERMISSIONS: `${adminEndPoint}/resource/updatePermissions`,
  CREATE_RESOURCE: `${adminEndPoint}/resource/create`,
  DELETE_RESOURCE: `${adminEndPoint}/resource/delete`,
  READ_RESOURCE: `${adminEndPoint}/resource/list`,
  SHOW_RESOURCE: `${adminEndPoint}/resource/show`,
  UPDATE_RESOURCE: `${adminEndPoint}/resource/update`,
  UPDATE_MULTI_RESOURCE_PERMISSIONS: `${adminEndPoint}/resource/updateMultipleResourcePermission`,
  CREATE_USER: `${adminEndPoint}/user/create`,
  READ_USER: `${adminEndPoint}/user/list`,
  UPDATE_USER: `${adminEndPoint}/user/update`,
  DISABLE_USER: `${adminEndPoint}/user/delete/{0}`,
  UPDATE_ROLE_USER: `${adminEndPoint}/user/{{id}}/updateRoles`,
  SHOW_USER: `${adminEndPoint}/user/show`,
  CREATE_PERMISSION: `${adminEndPoint}/permission/create`,
  READ_PERMISSION: `${adminEndPoint}/permission/list`,
  UPDATE_PERMISSION: `${adminEndPoint}/permission/update`,
  DELETE_PERMISSION: `${adminEndPoint}/permission/delete`,
  SHOW_PERMISSION: `${adminEndPoint}/permission/show`,
  CREATE_ROLE: `${adminEndPoint}/role/create`,
  READ_ROLE_LIST: `${adminEndPoint}/role/list`,
  UPDATE_ROLE: `${adminEndPoint}/role/update`,
  DELETE_ROLE: `${adminEndPoint}/role/delete`,
  SHOW_ROLE: `${adminEndPoint}/role/show`,
  UPDATE_ROLE_ACCESS: `${adminEndPoint}/role/{{id}}/updateRoleAccess`,
  CREATE_ROUTE: `${adminEndPoint}/route/create`,
  READ_ROUTE_LIST: `${adminEndPoint}/route/list`,
  READ_MODULE_LIST: `${adminEndPoint}/role/get-modules`,
  UPDATE_ROUTE: `${adminEndPoint}/route/update`,
  DELETE_ROUTE: `${adminEndPoint}/route/delete`,
  SHOW_ROUTE: `${adminEndPoint}/route/show`,
  UPDATE_SUB_ROUTE: `${adminEndPoint}/route/{{id}}/updateSubRoutes`,
  PERMISSIONS: `${adminEndPoint}/api/permissions`,
  CREATE_DRUG: `${adminEndPoint}/drug/create`,
  CREATE_HOSPITAL: `${adminEndPoint}/hospital/create`,
  READ_HOSPITAL: `${adminEndPoint}/hospital/list`,
  UPDATE_HOSPITAL: `${adminEndPoint}/hospital/update`,
  SHOW_HOSPITAL: `${adminEndPoint}/hospital/get`,
  DELETE_HOSPITAL: `${adminEndPoint}/hospital/delete`,
  CREATE_MANUFACTURER: `${adminEndPoint}/manufacturer/create`,
  READ_MANUFACTURER: `${adminEndPoint}/manufacturer/list`,
  ALL_MANUFACTURER: `${adminEndPoint}/manufacturer/full-list`,
  READ_DRUG: `${adminEndPoint}/drug/list`,
  DELETE_DRUG: `${adminEndPoint}/drug/delete`,
  UPDATE_DRUG: `${adminEndPoint}/drug/update`,
  SHOW_DRUG: `${adminEndPoint}/drug/get`,
  TOGGLE_DRUG_VISIBILITY: `${adminEndPoint}/drug/toggle-drug-visibility`,
  UPDATE_MANUFACTURER: `${adminEndPoint}/manufacturer/update`,
  SHOW_MANUFACTURER: `${adminEndPoint}/manufacturer/get`,
  DELETE_MANUFACTURER: `${adminEndPoint}/manufacturer/delete`,
  CREATE_DOCTOR: `${adminEndPoint}/hospital-doctor-info/create`,
  CREATE_BULK_DOCTOR: `${adminEndPoint}/hospital-doctor-info/create/bulk`,
  UPDATE_DOCTOR: `${adminEndPoint}/hospital-doctor-info/update`,
  SHOW_DOCTOR: `${adminEndPoint}/hospital-doctor-info/get`,
  READ_DOCTOR: `${adminEndPoint}/hospital-doctor-info/list`,
  DELETE_DOCTOR: `${adminEndPoint}/hospital-doctor-info/delete`,
  READ_RESOURCE_PERMISSION_LIST: `${adminEndPoint}/resource-permission/list`,
  CREATE_LENDER: `${adminEndPoint}/lender/create`,
  READ_LENDER: `${adminEndPoint}/lender/list`,
  UPDATE_LENDER: `${adminEndPoint}/lender/update`,
  DELETE_LENDER: `${adminEndPoint}/lender/delete`,
  SHOW_LENDER: `${adminEndPoint}/lender/get`,
  READ_PROGRAM: `${adminEndPoint}/program/list`,
  CREATE_PROGRAM: `${adminEndPoint}/program/create`,
  UPDATE_PROGRAM: `${adminEndPoint}/program/update`,
  DELETE_PROGRAM: `${adminEndPoint}/program/delete`,
  SHOW_PROGRAM: `${adminEndPoint}/program/get`,
  FORGOT_PASSWORD: `${adminEndPoint}/user/forgot-password`,
  CONTACT_SUPPORT: `${adminEndPoint}/user/contact-support`,
  GET_USER: `${adminEndPoint}/user/get-user`,
  ADD_HOLIDAY: `${adminEndPoint}/admin/add-holiday`,
  LIST_HOLIDAYS_FOR_YEAR: `${adminEndPoint}/admin/list-holidays-for-year`,
  POPULATE_SUNDAYS_FOR_YEAR: `${adminEndPoint}/admin/populate-sundays-for-year`,
  GET_MEDICATION_SCHEDULE: `${adminEndPoint}/schedule/list/{drugId}`,
  UPDATED_MEDICATION_SCHEDULE: `${adminEndPoint}/schedule/update`,
  GET_USER_DEVICES: `${adminEndPoint}/user/devices`,
  CREATE_HOSPITAL_IP_CONFIG: `${adminEndPoint}/hospital-configs/create`,
  GET_ALL_HOSPITALS_IP_CONFIG: `${adminEndPoint}/hospital-configs/get/all`,
  GET_SINGLE_HOSPITAL_IP_CONFIG: `${adminEndPoint}/hospital-configs/get/{0}`,
  UPDATE_HOSPITAL_IP_CONFIG: `${adminEndPoint}/hospital-configs/update/{0}`,
  DELETE_HOSPITAL_IP_CONFIG: `${adminEndPoint}/hospital-configs/delete/{0}`,
  MOBILE_VERSION_LIST_BACKEND: `${adminEndPoint}/version-support/backend-version/list`,
  CREATE_MOBILE_VERSION_BACKEND: `${adminEndPoint}/version-support/backend-version/create`,
  UPDATE_MOBILE_VERSION_BACKEND: `${adminEndPoint}/version-support/backend-version/update`,
  GET_MOBILE_VERSION_BACKEND: `${adminEndPoint}/version-support/backend-version/{0}`,
  DELETE_MOBILE_VERSION_BACKEND: `${adminEndPoint}/version-support/backend-version/delete/{0}`,
  MOBILE_VERSION_LIST_ANDROID: `${adminEndPoint}/version-support/android-version/list`,
  CREATE_MOBILE_VERSION_ANDROID: `${adminEndPoint}/version-support/android-version/create`,
  UPDATE_MOBILE_VERSION_ANDROID: `${adminEndPoint}/version-support/android-version/update`,
  GET_MOBILE_VERSION_ANDROID: `${adminEndPoint}/version-support/android-version/{0}`,
  DELETE_MOBILE_VERSION_ANDROID: `${adminEndPoint}/version-support/android-version/delete/{0}`,
  MOBILE_VERSION_LIST_IOS: `${adminEndPoint}/version-support/ios-version/list`,
  CREATE_MOBILE_VERSION_IOS: `${adminEndPoint}/version-support/ios-version/create`,
  UPDATE_MOBILE_VERSION_IOS: `${adminEndPoint}/version-support/ios-version/update`,
  GET_MOBILE_VERSION_IOS: `${adminEndPoint}/version-support/ios-version/{0}`,
  DELETE_MOBILE_VERSION_IOS: `${adminEndPoint}/version-support/ios-version/delete/{0}`,
  VERSION_MAPPING_UPDATE: `${adminEndPoint}/version-support/backend-version/add-mapping`,
  GET_VERSION_MAPPING: `${adminEndPoint}/version-support/backend-version/{0}/mappings`,

  //PHARMA-APIS
  PATIENT_RECRUITMENT_AND_CONVERSION: `${pharmaEndPoint}/patientrecruitment`,
  NEW_PATIENT_STATS: `${pharmaEndPoint}/newpatientstats`,
  PATIENT_LONGITUDINALITY: `${pharmaEndPoint}/patientlongitudinality`,
  SURVIVAL_AND_RESPONSE: `${pharmaEndPoint}/survivalandresponse`,
  DISCONTINUATION_AND_ADVERSE_EVENTS: `${pharmaEndPoint}/discontinuationandadverseevents`,
  PATIENT_REPORTED_OUTCOMES: `${pharmaEndPoint}/patientreportedoutcomes`,
  INDIVIDUAL_PATIENT_DATA: `${pharmaEndPoint}/individualpatientdata`,
  SALES_AND_FREE_PACKS: `${pharmaEndPoint}/salesandfreepacks`,
  PER_PATIENT_REVENUE: `${pharmaEndPoint}/perpatientrevenue`,
  //DOCUMENT_API
  UPLOAD_DOCUMENT: `${documentEndPoint}/upload-document-for-applicant`,
  ME_UPLOAD_DOCUMENT_PATIENT: `${documentEndPoint}/mango-executive/upload-document-for-patient`,
  READ_DOCUMENT: `${documentEndPoint}/list`,
  DOWNLOAD_DOCUMENT: `${documentEndPoint}/get`,
  DOCUMENT_DATA: `${documentEndPoint}/get-data`,
  REQUIRED_DOCUMENT: `${documentEndPoint}/required-documents`,
  DELETE_DOCUMENT: `${documentEndPoint}/delete`,
  UPLOAD_DOCUMENT_PATIENT: `${documentEndPoint}/upload-document-for-patient`,
  //DOCTOR_API
  DOCTOR_PATIENTS: `${doctorEndPoint}/your-patients`,
  GET_DOCTOR_BY_HOSPITAL_ID: `${doctorEndPoint}/all-doctors-by-hospital`,
  MASTER_DATA_ADMIN: `${adminEndPoint}/api/master-data`,
  //GENERAL
  REGISTER_URL: `admin/realms/{{realm}}/users`,
  GET_CSRF_TOKEN: '/csrf',
  VBC_GATEWAY: '/vbc-gateway',
};
